#!/usr/bin/bash
# Beautiful approach:
# 1) Try to have the class or function as independent as possible during development.
# 2) For every class developed, create the test case before moving to the next.These are unit tests.
# When you are done, and code is sorted end to end, then develop a combined integration-testing.

# Running tests using Substring approach, so no need of many files for each class created.
# https://www.tutorialspoint.com/pytest/pytest_substring_matching_of_test_names.htm

# You can use markers to group the tests
# https://www.tutorialspoint.com/pytest/pytest_grouping_the_tests.htm
python -m pytest -k Chat -v tests/test_client_modules.py
python -m pytest -k CreateQuery -v tests/test_client_modules.py
python -m pytest -k DataBaseQuery -v tests/test_server_modules.py
# python -m pytest -v tests/test_client_Chat_class.py
# python -m pytest -v tests/test_server_DataBaseQuery_class.py